# Generated by Django 6.0.7 on 2026-07-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(default='Sample Instruction'),
            preserve_default=False,
        ),
    ]
